(() => {
  'use strict';

  const wordCatalog = Array.isArray(window.VORDIK_WORD_CATALOG) ? window.VORDIK_WORD_CATALOG : [];
  const animalWords = wordCatalog
    .filter((entry) => Array.isArray(entry.collections) && entry.collections.includes('animals'))
    .map((entry) => [entry.word, entry.translation]);
  const travelWords = (Array.isArray(window.VORDIK_TRAVEL_WORDS) ? window.VORDIK_TRAVEL_WORDS : [])
    .map(([word, translation]) => [word, translation]);
  const moneyWords = (Array.isArray(window.VORDIK_MONEY_WORDS) ? window.VORDIK_MONEY_WORDS : [])
    .map(([word, translation]) => [word, translation]);
  const foodWords = (Array.isArray(window.VORDIK_FOOD_WORDS) ? window.VORDIK_FOOD_WORDS : [])
    .map(([word, translation]) => [word, translation]);

  window.VORDIK_COLLECTIONS = [
    {
      id: 'animals',
      title: 'Животные',
      description: 'Животные, птицы, насекомые и слова для описания дикой природы.',
      image: './images/collections/animals.png',
      words: animalWords,
    },
    {
      id: 'travel',
      title: 'Путешествия',
      description: 'Лексика для поездок, транспорта, проживания, ориентирования и аэропорта.',
      image: './images/collections/travel.png',
      words: travelWords,
    },
    {
      id: 'money',
      title: 'Деньги',
      description: 'Слова о покупках, банках, платежах, доходах и личных финансах.',
      image: './images/collections/money.png',
      words: moneyWords,
    },
    {
      id: 'food',
      title: 'Еда и рестораны',
      description: 'Слова о продуктах, приготовлении еды, заказах и общении в ресторане.',
      image: './images/collections/food.png',
      words: foodWords,
    },
    {
      id: 'communication',
      title: 'Знакомство и общение',
      description: 'Самые нужные слова для знакомства, приветствия и простого разговора.',
      words: [
        ['hello', 'привет'],
        ['hi', 'привет'],
        ['goodbye', 'до свидания'],
        ['please', 'пожалуйста'],
        ['thanks', 'спасибо'],
        ['pardon', 'извините'],
        ['sorry', 'прости / извините'],
        ['welcome', 'добро пожаловать'],
        ['name', 'имя'],
        ['friend', 'друг'],
        ['meet', 'знакомиться'],
        ['introduce', 'представлять'],
        ['speak', 'говорить'],
        ['understand', 'понимать'],
        ['repeat', 'повторять'],
        ['conversation', 'разговор'],
        ['acquaintance', 'знакомство'],
        ['surname', 'фамилия'],
        ['country', 'страна'],
        ['later', 'позже'],
      ],
    },
    {
      id: 'family',
      title: 'Семья и люди',
      description: 'Слова для рассказа о семье, близких людях и отношениях.',
      words: [
        ['family', 'семья'],
        ['mother', 'мама'],
        ['father', 'папа'],
        ['parents', 'родители'],
        ['sister', 'сестра'],
        ['brother', 'брат'],
        ['daughter', 'дочь'],
        ['son', 'сын'],
        ['child', 'ребёнок'],
        ['children', 'дети'],
        ['husband', 'муж'],
        ['wife', 'жена'],
        ['grandmother', 'бабушка'],
        ['grandfather', 'дедушка'],
        ['relative', 'родственник'],
        ['friend', 'друг'],
        ['colleague', 'коллега'],
        ['neighbour', 'сосед'],
        ['relationship', 'отношения'],
        ['married', 'женат / замужем'],
      ],
    },
    {
      id: 'home',
      title: 'Дом и повседневная жизнь',
      description: 'Основные слова о доме, комнатах и ежедневных бытовых делах.',
      words: [
        ['home', 'дом'],
        ['room', 'комната'],
        ['kitchen', 'кухня'],
        ['bedroom', 'спальня'],
        ['bathroom', 'ванная комната'],
        ['door', 'дверь'],
        ['window', 'окно'],
        ['table', 'стол'],
        ['chair', 'стул'],
        ['bed', 'кровать'],
        ['light', 'свет'],
        ['key', 'ключ'],
        ['clean', 'убирать / чистый'],
        ['cook', 'готовить'],
        ['wash', 'мыть'],
        ['sleep', 'спать'],
        ['awake', 'просыпаться'],
        ['dress', 'одеваться'],
        ['breakfast', 'завтракать'],
        ['bedtime', 'время сна'],
      ],
    },
    {
      id: 'city',
      title: 'Город и транспорт',
      description: 'Слова для передвижения по городу, поездок и поиска нужного места.',
      words: [
        ['city', 'город'],
        ['street', 'улица'],
        ['road', 'дорога'],
        ['bus', 'автобус'],
        ['train', 'поезд'],
        ['taxi', 'такси'],
        ['station', 'станция'],
        ['stop', 'остановка'],
        ['subway', 'метро'],
        ['ticket', 'билет'],
        ['map', 'карта'],
        ['traffic', 'дорожное движение'],
        ['left', 'налево'],
        ['right', 'направо'],
        ['straight', 'прямо'],
        ['near', 'рядом'],
        ['far', 'далеко'],
        ['direction', 'направление'],
        ['locate', 'находить'],
        ['ride', 'поездка'],
      ],
    },
    {
      id: 'shopping',
      title: 'Покупки и деньги',
      description: 'Основные слова для магазинов, оплаты и выбора товаров.',
      words: [
        ['shop', 'магазин'],
        ['buy', 'покупать'],
        ['sell', 'продавать'],
        ['price', 'цена'],
        ['money', 'деньги'],
        ['cash', 'наличные'],
        ['card', 'банковская карта'],
        ['size', 'размер'],
        ['colour', 'цвет'],
        ['cheap', 'дешёвый'],
        ['expensive', 'дорогой'],
        ['discount', 'скидка'],
        ['receipt', 'чек'],
        ['change', 'сдача'],
        ['fitting', 'примерка'],
        ['open', 'открыто'],
        ['closed', 'закрыто'],
        ['cost', 'стоимость'],
        ['payment', 'оплата'],
        ['available', 'доступный'],
      ],
    },
    {
      id: 'work',
      title: 'Работа и учёба',
      description: 'Слова для рабочего общения, учёбы, встреч и выполнения задач.',
      words: [
        ['work', 'работа / работать'],
        ['job', 'работа / должность'],
        ['office', 'офис'],
        ['company', 'компания'],
        ['colleague', 'коллега'],
        ['manager', 'руководитель'],
        ['meeting', 'встреча'],
        ['task', 'задача'],
        ['project', 'проект'],
        ['deadline', 'крайний срок'],
        ['document', 'документ'],
        ['email', 'электронное письмо'],
        ['call', 'звонок'],
        ['study', 'учиться'],
        ['learn', 'изучать'],
        ['question', 'вопрос'],
        ['answer', 'ответ'],
        ['explain', 'объяснять'],
        ['assist', 'помогать'],
        ['schedule', 'расписание'],
      ],
    },
    {
      id: 'health',
      title: 'Здоровье и экстренные ситуации',
      description: 'Важные слова для обращения к врачу и получения срочной помощи.',
      words: [
        ['health', 'здоровье'],
        ['doctor', 'врач'],
        ['hospital', 'больница'],
        ['pharmacy', 'аптека'],
        ['medicine', 'лекарство'],
        ['pain', 'боль'],
        ['headache', 'головная боль'],
        ['fever', 'высокая температура'],
        ['cough', 'кашель'],
        ['allergy', 'аллергия'],
        ['sick', 'больной'],
        ['hurt', 'болеть / причинять боль'],
        ['accident', 'несчастный случай'],
        ['emergency', 'чрезвычайная ситуация'],
        ['ambulance', 'скорая помощь'],
        ['help', 'помощь'],
        ['caution', 'осторожность'],
        ['nausea', 'тошнота'],
        ['treatment', 'лечение'],
        ['rescue', 'спасение'],
      ],
    },
    {
      id: 'emotions',
      title: 'Эмоции и выражение мнения',
      description: 'Слова для описания чувств, желаний и собственного мнения.',
      words: [
        ['happy', 'счастливый'],
        ['sad', 'грустный'],
        ['angry', 'злой'],
        ['afraid', 'испуганный'],
        ['tired', 'уставший'],
        ['excited', 'взволнованный'],
        ['surprised', 'удивлённый'],
        ['worried', 'обеспокоенный'],
        ['calm', 'спокойный'],
        ['bored', 'скучающий'],
        ['love', 'любить'],
        ['like', 'нравиться'],
        ['dislike', 'не нравиться'],
        ['want', 'хотеть'],
        ['hope', 'надеяться'],
        ['think', 'думать'],
        ['agree', 'соглашаться'],
        ['disagree', 'не соглашаться'],
        ['believe', 'считать'],
        ['opinion', 'мнение'],
      ],
    },
  ];

})();
